GET http://localhost:8888/api/sensors
Accept: application/json
###
GET http://localhost:8888/api/sensors/1
Accept: application/json
###
GET http://localhost:8888/api/sensors/5
Accept: application/json
###
HEAD http://localhost:8888/api/sensors
###
HEAD http://localhost:8888/api/sensors/1
###
HEAD http://localhost:8888/api/sensors/5
###
PUT http://localhost:8888/api/sensors/1
Content-Type: application/json

{
    "value":23
}
###
PUT http://localhost:8888/api/sensors/2
Content-Type: application/json

{
    "value":23
}
###
OPTIONS http://localhost:8888/api/sensors
###
OPTIONS http://localhost:8888/api/sensors/0
###
OPTIONS http://localhost:8888/api/sensors/5

